# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Activity.create!(title: "Hang gliding", description: "Hang gliding is an air sport in which a pilot flies a light and non-motorized foot-launch aircraft called a hang glider. Most modern hang gliders are made of an aluminium alloy or composite frame covered with synthetic sailcloth to form a wing. The pilot is ensconced in a harness suspended from the airframe, and exercises control by shifting body weight in opposition to a control frame, but other devices, including modern aircraft flight control systems, may be used. In the sport's early days, pilots were restricted to gliding down small hills on low-performance hang gliders. However, modern technology gives pilots the ability to soar for hours, gain thousands of metres of altitude in thermal updrafts, perform aerobatics, and glide cross-country for hundreds of kilometres. The Fédération Aéronautique Internationale and national airspace governing organizations control some regulatory aspects of hang gliding. Obtaining the safety benefits of being instructed is highly recommended.", image_url: "hanggliding.jpg", price: 50.00)
Activity.create!(title: "Mountaineering", description: "The term mountaineering describes the sport of mountain climbing, including ski mountaineering. Hiking in the mountains can also be a simple form of mountaineering when it involves scrambling, or short stretches of the more basic grades of rock climbing, as well as crossing glaciers. While mountaineering began as attempts to reach the highest point of unclimbed big mountains it has branched into specializations that address different aspects of the mountain and consists of three areas: rock-craft, snow-craft and skiing, depending on whether the route chosen is over rock, snow or ice. All require experience, athletic ability, and technical knowledge to maintain safety. Mountaineering is often called Alpinism, especially in European languages, which implies climbing with difficulty such high mountains as the Alps. A mountaineer with such great skill is called an Alpinist. The word alpinism was born in the 19th century to refer to climbing for the purpose of enjoying climbing itself as a sport or recreation, distinct from merely climbing while hunting or as a religious pilgrimage that had been done generally at that time. The UIAA or Union Internationale des Associations d'Alpinisme is the world governing body in mountaineering and climbing, addressing issues like access, medical, mountain protection, safety, youth and ice climbing.", image_url: "mountaineering.jpg", price: 500.00)
Activity.create!(title: "Diving", description: "Diving is the sport of jumping or falling into water from a platform or springboard, sometimes while performing acrobatics. Diving is an internationally recognized sport that is part of the Olympic Games. In addition, unstructured and non-competitive diving is a recreational pastime. Diving is one of the most popular Olympic sports with spectators. Competitors possess many of the same characteristics as gymnasts and dancers, including strength, flexibility, kinaesthetic judgment and air awareness. Some professional divers were originally gymnasts or dancers as both the sports have similar characteristics to diving.", image_url: "diving.jpg", price: 250.00)
Activity.create!(title: "Windsurfing", description: "Windsurfing is a surface water sport that combines elements of surfing and sailing. It consists of a board usually 2 to 3 meters long, with a volume of about 60 to 250 liters, powered by wind on a sail. The rig is connected to the board by a free-rotating universal joint and consists of a mast, 2-sided boom and sail. The sail area generally ranges from 2.5 m2 to 12 m2 depending on the conditions, the skill of the sailor and the type of windsurfing being undertaken.
Windsurfing can be said to straddle both the laid-back culture of surf sports and the more rules-based environment of sailing. Although it might be considered a minimalistic version of a sailboat, windsurfing offers experiences that are outside the scope of other sailing craft designs. Windsurfers can perform jumps, inverted loops, spinning maneuvers, and other \"freestyle\" moves that cannot be matched by any sailboat. Windsurfers were the first to ride the world's largest waves, such as Jaws on the island of Maui, and, with very few exceptions, it was not until the advent of tow-in surfing that waves of that size became accessible to surfers on more traditional surfboards. Extreme waves aside, many expert windsurfers will ride the same waves as wavesurfers do (wind permitting) and are themselves usually very accomplished without a rig on a conventional surfboard.
Windsurfing is predominately undertaken on a non-competitive basis. Organised competition does take place at all levels across the world and typical formats for competitive windsurfing include Formula Windsurfing, speed sailing, slalom, course racing, wave sailing, superX, and freestyle. These events are exciting to watch as sailors push the limits both physically and creatively with moves that look as impossible as thinking them up in the first place.
The boom of the 1980s led windsurfing to be recognized as an Olympic sport in 1984. However, windsurfing's popularity saw a sharp decline in the mid-1990s, thanks to licensing battles, and equipment becoming more specialized and requiring more expertise to sail. The sport experienced a modest revival, as new beginner-friendly designs became available. Further pressure came as a proportion of avid windsurfers took up the similar sport of kitesurfing.", price: 150.00)
